# Generated by Django 5.2.1 on 2025-05-21 23:56

import useraccount.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', useraccount.models.CustomUserManager()),
            ],
        ),
    ]
